version: "2"
services:

  nodejs:
    build: .
    environment:
      - NODE_PORT=4002
    working_dir: /var/www/api

  webserver:
    image: nginx
    environment:
      - NODE_HOST=nodejs
      - NODE_PORT=4002
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./docker/nginx/:/nginx
    command: /bin/bash -c "envsubst < /nginx/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443